### ISSUE TITLE
Anti-Feature: Remove the Notification

### ISSUE THREAD

**Issue by svoop** [tommasongr/nova-rails#26]
Would it be possible to drop the notification every time a Rails project is opened? No other extension I know does this and for debugging, logging a line to the extension console would be more than enough IMO.

**Comment by tommasongr** [comment]
Hi there!

Actually this is already possible by unchecking the "Status Notifications" option in the settings. It can be done globally or per project.

<img width="875" alt="CleanShot 2022-11-22 at 14 50 02@2x" src="https://user-images.githubusercontent.com/25225746/203330922-2a1ca6c6-39d5-4b26-a333-23e0e66b7534.png">

Anyway the notification was not intended for debugging but for notifying the user the ability to use Rails specific features. Since the extension provides tools also for other ruby based projects/frameworks I thought it would have been helpful.

Let me know if this solution is ok for you.
